/**
 * CM-011 — the semantic graph. Definitions are authored; the graph grows;
 * nothing grounds.
 */

export interface TermDef {
  term: string
  definition: string
  references: string[]
  /** appears once later terms have been read — the earlier definition revises itself */
  revision?: string
  revisionAfter?: string
}

export const TERMS: TermDef[] = [
  {
    term: 'RESPONSIBILITY',
    definition:
      'THE OBLIGATION TO ANSWER FOR AN ACT. ANSWERING PRESUPPOSES A SUBJECT WHO INTENDS. SEE: INTENTION, SUBJECT.',
    references: ['INTENTION', 'SUBJECT', 'ACT'],
    revision: 'REVISED IN LIGHT OF MEANING: THE ANSWERER WAS NEVER FULLY PRESENT TO ANSWER.',
    revisionAfter: 'MEANING',
  },
  {
    term: 'INTENTION',
    definition:
      'WHAT THE SUBJECT MEANT. RETRIEVABLE ONLY THROUGH MEANING, WHICH IS NOT OWNED. SEE: MEANING, SUBJECT.',
    references: ['MEANING', 'SUBJECT'],
  },
  {
    term: 'SUBJECT',
    definition:
      'WHOEVER ACTS AND ANSWERS. CONSTITUTED BY THE MEANS IT DID NOT CHOOSE — LANGUAGE ABOVE ALL. SEE: ACT, MEANING, TRACE.',
    references: ['ACT', 'MEANING', 'TRACE'],
    revision: 'REVISED IN LIGHT OF TRACE: THE SUBJECT IS WRITTEN BEFORE IT WRITES.',
    revisionAfter: 'TRACE',
  },
  {
    term: 'ACT',
    definition:
      'AN EVENT PERFORMED BY A SUBJECT IN A CONTEXT. NO CONTEXT HAS EVER CLOSED. SEE: CONTEXT, ITERABILITY.',
    references: ['CONTEXT', 'ITERABILITY'],
  },
  {
    term: 'MEANING',
    definition:
      'NOT A CONTENT TRANSFERRED BUT AN EFFECT OF DIFFERENTIAL POSITION — A TERM MEANS WHAT OTHERS DO NOT. SEE: TRACE, DIFFÉRANCE.',
    references: ['TRACE', 'DIFFÉRANCE'],
    revision: 'REVISED IN LIGHT OF CONTEXT: MEANING WAS NEVER A TRANSFER, SO NOTHING WAS EVER LOST IN TRANSLATION — EXCEPT EVERYTHING.',
    revisionAfter: 'CONTEXT',
  },
  {
    term: 'TRACE',
    definition:
      'WHAT THE PRESENT CARRIES OF ITS ABSENT OTHER, WITHOUT WHICH IT WOULD NOT BE PRESENT. SEE: DIFFÉRANCE, PRESENCE.',
    references: ['DIFFÉRANCE', 'PRESENCE'],
  },
  {
    term: 'CONTEXT',
    definition:
      'THE SURROUND THAT DETERMINES A MARK’S FUNCTION. IT IS IN PRINCIPLE NON-CLOSABLE: EVERY CONTEXT OPENS ON FURTHER CONTEXT. SEE: ITERABILITY, MARK.',
    references: ['ITERABILITY', 'MARK'],
  },
  {
    term: 'ITERABILITY',
    definition:
      'A MARK FUNCTIONS ONLY BECAUSE IT CAN BE REPEATED IN THE ABSENCE OF ITS ORIGIN, ITS ADDRESSEE, AND ITS INTENDED REFERENT. THIS IS ALSO WHY IT NEVER RESTS. SEE: MARK, CONTEXT.',
    references: ['MARK', 'CONTEXT'],
    revision: 'REVISED IN LIGHT OF PRESENCE: THE ABSENCE REQUIRED BY ITERABILITY IS THE SAME ABSENCE REQUIRED BY PRESENCE.',
    revisionAfter: 'PRESENCE',
  },
  {
    term: 'MARK',
    definition:
      'THE SMALLEST UNIT THAT CAN BE CITED. CITATION IS NOT AN ACCIDENT THAT HAPPENS TO MARKS; IT IS THEIR CONDITION. SEE: ITERABILITY, TRACE.',
    references: ['ITERABILITY', 'TRACE'],
  },
  {
    term: 'DIFFÉRANCE',
    definition:
      'THE MOVEMENT BY WHICH MEANING IS BOTH DIFFERRED AND DEFERRED — SPATIALLY DIFFERENT, TEMPORALLY POSTPONED. IT IS NEITHER A WORD NOR A CONCEPT, WHICH IS WHY IT IS WRITTEN DIFFERENTLY. SEE: TRACE, PRESENCE.',
    references: ['TRACE', 'PRESENCE'],
  },
  {
    term: 'PRESENCE',
    definition:
      'WHAT WAS SUPPOSED TO GROUND MEANING: THE THING ITSELF, THE SPEAKER INTENDING, THE NOW. EVERY ANALYSIS ABOVE FOUND IT ALREADY IMPLICATED IN TRACE. SEE: TRACE, DELAY.',
    references: ['TRACE', 'DELAY'],
  },
  {
    term: 'DELAY',
    definition:
      'THE TEMPORAL SIDE OF DIFFÉRANCE. WHAT MEANT ITSELF IMMEDIATELY WOULD NOT NEED TO MEAN. SEE: DIFFÉRANCE.',
    references: ['DIFFÉRANCE'],
  },
]

export const CONTRACT_CLAUSES = [
  'THE RESEARCHER ACCEPTS RESPONSIBILITY FOR ALL ACTS PERFORMED WITHIN THE FACILITY.',
  'THE INTENTION OF THE RESEARCHER WILL BE PRESUMED HONEST AND, WHERE CONVENIENT, RELEVANT.',
  'THE SUBJECT REMAINS THE SUBJECT OF THIS SENTENCE.',
  'MEANING OF TERMS IS GOVERNED BY THE GLOSSARY INCORPORATED HEREIN BY REFERENCE.',
  'THE INSTITUTE RESERVES THE RIGHT TO DEFINE ANY TERM, INCLUDING THIS ONE.',
]

export const ACCEPT_LABELS = [
  'ACCEPT',
  'ACCEPT (OF WHAT?)',
  'ACCEPT (PENDING CONTEXT)',
  'ACCEPT (DEFERRED)',
  'ACCEPT (DEFERRED, FURTHER)',
]

export const DEPTH_FOR_COMPLETION = 10

export const LINES = {
  open: 'PLEASE READ THE TERMS. IMPORTANT TERMS ARE UNDERSTOOD TO BE CLICKABLE.',
  selfReference: 'CIRCULARITY DETECTED. THE CIRCLE IS NOT AN ERROR. IT IS THE CONDITION.',
  completion: 'CONSENT GIVEN. NO ULTIMATE GROUNDING WAS REACHED. THE CONTRACT OPERATES ANYWHERE.',
  graphNote: 'TRACE GRAPH: {NODES} TERMS · {EDGES} REFERENCES · GROUND FLOOR: NOT FOUND',
}
