/** MA-04 — attention economy (pure timing). */
export const REVELATIONS = [
  'THE OBJECT IS HELD WITHOUT BEING HELD.',
  'IT TURNS SLOWLY, AS THINGS DO WHEN NO ONE ASKS THEM TO.',
  'ATTENTION IS NOT EXTRACTION. THE OBJECT KEEPS WHAT YOU DO NOT TAKE.',
  'EVERY APPARATUS IN THIS FACILITY REWARDS TOUCH. THIS ONE FILES IT AS INTERRUPTION.',
  'WHAT YOU ARE WATCHING IS YOUR OWN REFUSAL TO GRASP.',
  'THE INSTITUTE CALLS THIS DATA. THE NAME IS A WEAKNESS.',
]

export const REVEAL_INTERVAL_MS = 9_000

/** Manipulation penalty: each touch delays the next revelation. */
export const PENALTY_MS = 6_000
export const RESUME_AFTER_IDLE_MS = 4_000
