/** MA-02 — mediated representations (pure data). */
export const REPRESENTATIONS = [
  'TEXTURE: GRANULAR, WARM TO PROXIMITY SENSORS.',
  'FIGURE: OUTLINED BY CONTRAST WITH ITS SURROUND. THE SURROUND IS MEDIATED.',
  'EXTENT: REPORTED IN INCHES, WHICH ARE ARBITRARY.',
  'DURATION: PERSISTS, REPORTEDLY. THE REPORT IS STRUCTURED BY MEMORY.',
  'CAUSE: INFERRED. THE INFERENCE USES CATEGORIES THE INSPECTOR SUPPLIED.',
  'THING-IN-ITSELF: FIELD RETURNS “NULL” — WHICH IS ITSELF A CATEGORY.',
]

export const MAX_INSPECTIONS = REPRESENTATIONS.length

export const WITHHELD =
  'THE RAW-OBJECT PANE CANNOT BE OPENED. EVERY PANE IS ANOTHER REPRESENTATION. THE INSPECTION IS WITHHELD.'
